export const queryKeys = {
    user: (username) => ["user", username],
    allUsers: () => ["user"],
    follow: (userId) => ["follow", userId],
    article: (slug) => ["article", slug],
    allArticles: () => ["articles"],
    articleList: (params = {}) => ["articles", params],
    allComments: () => ["comments"],
    comments: (articleId) => ["comments", articleId],
    likes: (articleId) => ["likes", articleId],
    save: (articleId) => ["save", articleId],
    lists: (authorId, articleId) => ["lists", authorId, articleId ?? null],
    userSaves: (userId) => ["userSaves", userId],
    userViews: (userId) => ["userViews", userId],
    exploreRecommendations: () => ["explore", "recommendations"],
    search: (q) => ["search", q],
    subscriptionFeed: () => ["articles", { filter: "subscriptions" }],
    following: (userId) => ["following", userId],
    followers: (userId) => ["followers", userId],
};